### ISSUE TITLE
Blend prompts broken since 2.3.0

### ISSUE THREAD

**Issue by mbaxter** [damian0815/compel#130]
## Summary

Blend prompts broken since 2.3.0: `_get_conditioning_for_flattened_prompt() got an unexpected keyword argument 'should_return_tokens'`

Any prompt that uses blend syntax (`("a", "b").blend(w1, w2)`) raises a `TypeError` in every release from **2.3.0 through 2.4.0** (the latest). Plain, non-blended prompts are unaffected.

## Root cause

`_get_conditioning_for_blend` (and the two cross-attention-control call sites) call `_get_conditioning_for_flattened_prompt` with a `should_return_tokens=True` keyword argument:

https://github.com/damian0815/compel/blob/main/src/compel/compel.py#L353
https://github.com/damian0815/compel/blob/main/src/compel/compel.py#L411
https://github.com/damian0815/compel/blob/main/src/compel/compel.py#L420

But `_get_conditioning_for_flattened_prompt`'s signature no longer accepts that parameter — it was dropped, without updating these three call sites.

This is a 2.2.1 → 2.3.0 regression, introduced by https://github.com/damian0815/compel/commit/777f0217a3b315c0e2443bb4a1d51c9582881455 ("optionally return tokenization info", part of #120). That commit's diff removes `should_return_tokens: bool=False` from `_get_conditioning_for_flattened_prompt`'s signature in one hunk, then in the very next hunk updates `_get_conditioning_for_blend` to call it with `should_return_tokens=True` — the two edits contradict each other within the same commit:

```diff
     def _get_conditioning_for_flattened_prompt(self,
                                                prompt: FlattenedPrompt,
-                                               should_return_tokens: bool=False
-                                               ) -> Union[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:
+                                               ) -> Tuple[torch.Tensor, torch.Tensor]:
         ...
     def _get_conditioning_for_blend(self, blend: Blend):
         conditionings_to_blend = []
+        tokenizations = []
         for i, flattened_prompt in enumerate(blend.prompts):
-            this_conditioning = self._get_conditioning_for_flattened_prompt(flattened_prompt)
+            this_conditioning, tokenization = self._get_conditioning_for_flattened_prompt(flattened_prompt, should_return_tokens=True)
```

| version | `_get_conditioning_for_flattened_prompt` signature | blend works? |
|---|---|---|
| 2.2.0, 2.2.1 | `(self, prompt, should_return_tokens: bool=False)` | ✅ |
| 2.3.0, 2.3.1, 2.4.0 (latest) | `(self, prompt)` — no such param | ❌ |
| `main` (unreleased) | `(self, prompt)` — no such param | ❌ (still broken) |

## Steps to reproduce

No GPU, no model download needed — a dummy tokenizer/text-encoder pair is enough to hit the code path:

```python
import torch
from compel import Compel

class DummyTokenizer:
    def __init__(self):
        self.tokens = ["a", "b", "<|bos|>", "<|pad|>", "<|eos|>"]
        self.bos_token_id, self.pad_token_id, self.eos_token_id = 2, 3, 4
        self.unk_token_id = self.eos_token_id
        self.model_max_length = 8

    def __call__(self, fragments, **kwargs):
        return {"input_ids": [
            [self.bos_token_id] + [self.tokens.index(w) for w in f.split(" ")] + [self.eos_token_id]
            for f in fragments
        ]}

    def convert_tokens_to_ids(self, toks):
        return [self.tokens.index(t) if t in self.tokens else self.unk_token_id for t in toks]

    def convert_ids_to_tokens(self, ids):
        return [self.tokens[i] for i in ids]

    def add_tokens(self, t):
        return 0

class DummyTransformer:
    def __init__(self):
        self.device = "cpu"
        self.dtype = torch.float32
        self.embeddings = [torch.randn(768) for _ in range(8)]

    def resize_token_embeddings(self, n=None):
        return self.embeddings

    def get_input_embeddings(self):
        return self.embeddings

    def __call__(self, input_ids, attention_mask=None, **kwargs):
        emb = torch.stack(self.embeddings)[input_ids.squeeze(0)].unsqueeze(0)
        class Out:
            last_hidden_state = emb
            hidden_states = [-emb, emb]
        return Out()

compel = Compel(tokenizer=DummyTokenizer(), text_encoder=DummyTransformer())
conditioning = compel('("a", "b").blend(0.6, 0.4)')
print("OK", conditioning.shape)
```

## Actual behavior

```
Traceback (most recent call last):
  ...
  File ".../compel/compel.py", line 167, in __call__
    output = self.build_conditioning_tensor(text_input, return_tokenization=True)
  File ".../compel/compel.py", line 125, in build_conditioning_tensor
    conditioning, tokenization, options = self.build_conditioning_tensor_for_conjunction(conjunction, return_tokenization=True)
  File ".../compel/compel.py", line 227, in build_conditioning_tensor_for_conjunction
    (this_conditioning, this_tokens), this_options = self.build_conditioning_tensor_for_prompt_object(p)
  File ".../compel/compel.py", line 264, in build_conditioning_tensor_for_prompt_object
    return self._get_conditioning_for_blend(prompt), {}
  File ".../compel/compel.py", line 353, in _get_conditioning_for_blend
    this_conditioning, tokenization = self._get_conditioning_for_flattened_prompt(flattened_prompt, should_return_tokens=True)
TypeError: Compel._get_conditioning_for_flattened_prompt() got an unexpected keyword argument 'should_return_tokens'
```

## Expected behavior

`compel('("a", "b").blend(0.6, 0.4)')` returns a conditioning tensor, same as it does on 2.2.1.

## Environment

- `compel`: reproduced on 2.3.0, 2.3.1, 2.4.0, and `main` @ (commit as of 2026-07-08)
- Last known-good release: **2.2.1**
- Python 3.12.1, `torch` 2.12.1 (though the dummy repro shows this is independent of torch/transformers version)

## Suggested fix

Either restore the `should_return_tokens` parameter to `_get_conditioning_for_flattened_prompt`'s signature (matching 2.2.x), or drop the now-stale `should_return_tokens=True` keyword argument from the three call sites (lines 353, 411, 420) — `_get_conditioning_for_flattened_prompt` already unconditionally does the tokens-returning thing internally, so the latter looks like the minimal fix.
